name: thaw
description: "A new Flutter project."
 
publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: '>=3.3.3 <4.0.0'

 
dependencies:
  flutter:
    sdk: flutter
 

 
  cupertino_icons: ^1.0.6 
  firebase_auth: ^5.0.0
  google_sign_in: ^6.2.1
  firebase_storage: ^12.0.1
  get: ^4.6.6
  firebase_app_check: ^0.3.0+1
  firebase_core: ^3.1.0
  carousel_slider: ^4.2.1
  equatable: ^2.0.5
  cloud_firestore: ^5.0.1
  file_picker: ^8.0.5
  buttons_tabbar: ^1.3.10
  image_picker: ^1.1.2
  shared_preferences: ^2.2.3
  animated_splash_screen: ^1.3.0
  lottie: ^3.1.2
  font_awesome_icon_class: ^0.0.6
  provider: ^6.1.2
  slide_action: ^0.0.2
  badges: ^3.1.2
  multi_select_flutter: ^4.1.3
  flutter_chips_input: ^2.0.0
  intl: ^0.19.0
  cached_network_image: ^3.3.1
  printing: ^5.11.1
  pdf: ^3.11.0
  path_provider: ^2.1.3
  flutter_launcher_icons: ^0.13.1
  url_launcher: ^6.3.0
 

flutter_icons:
  android: true
  ios: true
  image_path: "assets/images/Generate_a_logo_75f1e5eb-f843-4e71-a763-daf800aa47e0-removebg-preview.png"
  
dev_dependencies:
  flutter_test:
    sdk: flutter

 

  flutter_lints: ^3.0.0
 
 
flutter:

 
  uses-material-design: true

  assets:
    - assets/images/

    - assets/icons/
    
    - assets/animation/

 
  fonts:
    - family: English
      fonts:

        - asset: assets/fonts/Sora/static/Sora-ExtraBold.ttf
          style: italic
          weight: 700
    - family: Burmese
      fonts:

        - asset: assets/fonts/Noto_Sans/static/NotoSans_Condensed-Bold.ttf
          style: italic
          weight: 700
