name: thaw
description: "A new Flutter project."
 
publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: '>=3.3.3 <4.0.0'

 
dependencies:
  flutter:
    sdk: flutter


 
  cupertino_icons: ^1.0.6
  firebase_auth: ^5.0.0
  google_sign_in: ^6.2.1
  firebase_storage: ^12.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter

 
  font_awesome_icon_class: ^0.0.6

  flutter_lints: ^3.0.0
  firebase_core: ^3.0.0
  carousel_slider: ^4.2.1

 
flutter:

 
  uses-material-design: true

  assets:
    - assets/images/
    - assets/icons/
    

 
  fonts:
    - family: English
      fonts:

        - asset: assets/fonts/Sora/static/Sora-ExtraBold.ttf
          style: italic
          weight: 700
 
